### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by IronMania** [fpommerening/fpommerening.github.io#2]
Hey,
i wanted to view your slides from devopenspace. Can you add documentation on how to find them in the readme?

thanks
Jörg

**Comment by fpommerening** [comment]
Hallo Jörg,

the slides are linked in the ReadMe of the DevOpenSpace 2018 Repo.
https://github.com/fpommerening/DevOpenSpace2018

Here is the direct Link to the slides:
https://fpommerening.github.io/DevOpenSpace2018/index.html#/

LG
Frank
